version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    rebase-strategy: "auto"
