#!/usr/bin/env bun
import { $ } from 'bun';
import { basename } from 'node:path';
import { CONFIG_PATHS, ENV_KEYS, loadConfig, serializeConfig } from './lib/wrangler-config';

/**
 * Single deploy path for local machines and CI.
 *
 * Generates wrangler.deploy.jsonc from the committed wrangler.jsonc with real
 * KV namespace IDs injected from the environment (GitHub Actions secrets in
 * CI; bun auto-loads .env.local locally), runs `wrangler deploy` against the
 * generated file, and syncs the NTFY_URL worker secret when present in the
 * environment. The committed config never holds real IDs.
 *
 * Flags:
 *   --generate-only   write wrangler.deploy.jsonc and exit (placeholders pass
 *                     through when the environment has no IDs, so fork PRs
 *                     can still dry-run builds)
 *   --dry-run         generate, then `wrangler deploy --dry-run`
 */
type Mode = 'deploy' | 'dry-run' | 'generate-only';

function resolveMode(argv: readonly string[]): Mode {
	if (argv.includes('--generate-only')) return 'generate-only';
	if (argv.includes('--dry-run')) return 'dry-run';
	return 'deploy';
}

async function generateDeployConfig(mode: Mode): Promise<void> {
	const config = await loadConfig();
	const namespace = config.kv_namespaces?.[0];
	if (!namespace) {
		console.error(`No kv_namespaces entry found in ${basename(CONFIG_PATHS.source)}`);
		process.exit(1);
	}

	const kvId = process.env[ENV_KEYS.kvId];
	const kvPreviewId = process.env[ENV_KEYS.kvPreviewId] ?? kvId;

	if (kvId !== undefined && kvId !== '' && kvPreviewId !== undefined && kvPreviewId !== '') {
		namespace.id = kvId;
		namespace.preview_id = kvPreviewId;
		console.log('Injected KV namespace IDs from environment.');
	} else if (mode === 'deploy') {
		console.error(`${ENV_KEYS.kvId} is not set. Run \`bun run setup\` first, or set it in the environment.`);
		process.exit(1);
	} else {
		console.log('No KV namespace IDs in environment; keeping placeholders.');
	}

	const header = `// Auto-generated by scripts/${basename(import.meta.filename)}. Do not edit.\n`;
	await Bun.write(CONFIG_PATHS.deploy, header + serializeConfig(config));
	console.log(`Wrote ${CONFIG_PATHS.deploy}`);
}

async function main(): Promise<void> {
	const mode = resolveMode(process.argv);
	await generateDeployConfig(mode);
	if (mode === 'generate-only') return;

	const deployArgs = mode === 'dry-run' ? ['--dry-run'] : [];
	await $`bun x wrangler deploy --config ${CONFIG_PATHS.deploy} ${deployArgs}`;
	if (mode === 'dry-run') return;

	const ntfyUrl = process.env[ENV_KEYS.ntfyUrl];
	if (ntfyUrl !== undefined && ntfyUrl !== '') {
		console.log(`Syncing ${ENV_KEYS.ntfyUrl} worker secret…`);
		await $`bun x wrangler secret put ${ENV_KEYS.ntfyUrl} --config ${CONFIG_PATHS.deploy} < ${new Response(ntfyUrl)}`;
	} else {
		console.log(`${ENV_KEYS.ntfyUrl} not in environment; skipping secret sync.`);
	}
}

await main();
