name: 'Code Coverage'

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npx vitest run --coverage

      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2.8.3
        with:
          name: 'Code Coverage Report'
          file-coverage-mode: changes
