name: 'Code Coverage'

on:
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: 'Install Node'
        uses: actions/setup-node@v6

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Code Coverage'
        run: npx vitest run --coverage

      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@3c50566c523e04813df28de8f7c48dd97d663f1c # v2
